- src/Iconv/Iconv.php
- src/Intl/Grapheme/Grapheme.php
- src/Mbstring/Mbstring.php
- src/Php54/Php54.php
- src/Php55/Php55.php
- src/Php55/Php55ArrayColumn.php
- src/Php56/Php56.php
- src/Php70/Php70.php
- src/Xml/Xml.php
Hi!
First of all, it is going to be a great lib!
Then, about PR - shouldn't internal classes be final where it is possible?
> Mark classes as final

- src/Mbstring/Mbstring.php
- tests/Mbstring/MbstringTest.php
If iconv can, our polyfill should also
> [Mbstring] Allow checking for all iconv supported charsets

- src/Iconv/composer.json
- src/Mbstring/composer.json
- src/Xml/composer.json
The key for suggestions is `suggest`, ref. https://getcomposer.org/doc/04-schema.md#suggest
> Fixed wrong schema in composer files

- src/Php56/bootstrap.php
> Fix #16 - gzopen() / gzopen64() - 32 bit builds of Ubuntu 14.04

- LICENSE
- src/Iconv/LICENSE
- src/Intl/Grapheme/LICENSE
- src/Intl/Icu/LICENSE
- src/Intl/Normalizer/LICENSE
- src/Mbstring/LICENSE
- src/Php54/LICENSE
- src/Php55/LICENSE
- src/Php56/LICENSE
- src/Php70/LICENSE
- src/Util/LICENSE
- src/Xml/LICENSE
> Update copyright year

- src/Php70/README.md
> fix typo in Readme 'compatibility notes'

- src/Apcu/bootstrap.php
> Add missing check for APCIterator

- src/Intl/Normalizer/Normalizer.php
- tests/Intl/Normalizer/NormalizerTest.php
> Normalizer fixes from @gitlost 

- src/Mbstring/Mbstring.php
- tests/Mbstring/MbstringTest.php
> Bypass iconv for some charsets in mb_strlen

- src/Apcu/bootstrap.php
> Provide APCUIterator for APCu 4.x users

- src/Mbstring/Mbstring.php
- tests/Mbstring/MbstringTest.php
> [Mbstring] Fix iconv_substr(): Detected an illegal character in input string

- src/Mbstring/Mbstring.php
- tests/Mbstring/MbstringTest.php
> [Mbstring] Add missing validation to mb_convert_case()

- .travis.yml
- src/Apcu/Apcu.php
- src/Apcu/bootstrap.php
- src/Util/TestListener.php
- tests/Apcu/ApcuTest.php
Fixes #94 
Detect if Zend Server's Data Cache is enabled, and work around it's lack of support for the array syntax.
> Fix apcu function when apc ones are polyfilled with Zend Server's Data Cache

- CHANGELOG.md
- src/Apcu/composer.json
> [Apcu] Add missing PSR-4 entry

- src/Iconv/Iconv.php
- tests/Iconv/IconvTest.php
> [iconv] make translit/ignore flags order-insensitive

- src/Mbstring/Mbstring.php
This one is implemented, but wasn't present in the list
> Add missing function to phpdoc

- appveyor.yml
- src/Util/LegacyTestListener.php
- src/Util/TestListener.php
- src/Util/TestListenerTrait.php
- tests/Apcu/ApcuTest.php
- tests/Iconv/IconvTest.php
- tests/Intl/Grapheme/GraphemeTest.php
- tests/Intl/Normalizer/NormalizerTest.php
- tests/Mbstring/MbstringTest.php
- tests/Php54/Php54Test.php
- tests/Php56/Php56Test.php
- tests/Php70/Php70Test.php
- tests/Php71/Php71Test.php
- tests/Php72/Php72Test.php
Replaces #106, fixes Bug-Debian: https://bugs.debian.org/882930
> Add compatibility with namespaced PHPUnit

- src/Ctype/composer.json
This is in line with other poly fills like mbstring
> Suggest ctype extension

- src/Php72/Php72.php
see : [symfony/symfony#27794](https://github.com/symfony/symfony/pull/27794).
> Checks the enviroment for Hyper Termianl on sapi_windows_vt100_support.

- CHANGELOG.md
- appveyor.yml
- src/Php73/Php73.php
- src/Php73/bootstrap.php
- tests/Php73/Php73Test.php
@mcfedr I'm wondering: wouldn't this be enough?
> Add hrtime() function

- src/Php73/bootstrap.php
- tests/Php73/Php73Test.php
RFC: https://wiki.php.net/rfc/array_key_first_last
Added to PHP in php/php-src@50516a6e1f357f63324ec76e26623f2a7185bd4f
> PHP 7.3: Add array_key_first and array_key_last functions

- tests/Php73/Php73Test.php
> skip ResourceBundle test on big endian systems

- .gitignore
- .php_cs.dist
- src/Mbstring/Mbstring.php
- src/Php72/Php72.php
- tests/Php72/Php72Test.php
as you requested, @nicolas-grekas
> DX: PHP CS Fixer configuration

- README.md
> Add a note about reducing overhead

- src/Php55/Php55.php
- tests/Php55/Php55Test.php
See https://twitter.com/CiPHPerCoder/status/1050427719941525504 for discussion
> Prevent DoS via long passwords

- tests/Intl/MessageFormatter/MessageFormatterTest.php
Fixes https://github.com/symfony/symfony/issues/29737 but in polyfill
> Replace gender by eye color

- src/Mbstring/Mbstring.php
- tests/Mbstring/MbstringTest.php
> [Mbstring ] fix mb_substr return type

- src/Intl/Grapheme/Grapheme.php
- src/Intl/Normalizer/Normalizer.php
- src/Intl/Normalizer/Resources/stubs/Normalizer.php
- src/Util/TestListenerForV7.php
- tests/Intl/Grapheme/GraphemeTest.php
- tests/Php72/Php72Test.php
- tests/Php73/Php73Test.php
and some cleanups found meanwhile
> [grapheme] fix handling negative offsets

- src/Mbstring/Mbstring.php
- tests/Intl/Normalizer/NormalizerTest.php
- tests/Mbstring/MbstringTest.php
Will fix the last failures on https://github.com/symfony/symfony/pull/33553
> [Mbstring] fix mb_strrpos with negative offset

- .github/composer-config.json
- appveyor.yml
Trying to make appveyor green.
> Bump composer on appveyor

- src/Intl/Grapheme/Grapheme.php
- tests/Intl/Grapheme/GraphemeTest.php
found via https://github.com/symfony/symfony/pull/33971
> support grapheme_extract() with negative $start

- tests/Uuid/UuidTest.php
fixes https://github.com/symfony/polyfill/pull/187#issuecomment-559123404
> [UUID] Fixed tests when the PECL is not available

- src/Uuid/Uuid.php
```
>…github.com/lyrixx/symfony-polyfill(master) php test.php
[Symfony][v4] 4.835s
>…github.com/lyrixx/symfony-polyfill(uuid) php test.php
[Symfony][v4] 1.558s
```
> [UUID] speedup implementation

- src/Uuid/Uuid.php
(all commits are actually independent)
> [UUID] Fix undefined variable in error message, and other minor fixes

- src/Uuid/Uuid.php
> Check for 32-bit PHP in uuid_generate_time() too

- composer.json
- src/Uuid/bootstrap.php
> [Uuid] fix constant definitions

- src/Intl/Idn/composer.json
> Raise minimum polyfill-php72 version in polyfill-intl-idn

- composer.json
- src/Php80/Php80.php
- src/Php80/bootstrap.php
- src/Util/TestListenerTrait.php
- src/bootstrap.php
- tests/Php80/Php80Test.php
The PHP8 polyfill has PHP7 as a minimum requirement.
> [PHP8] add type hints

- README.md
- src/Php80/Php80.php
- src/Php80/README.md
- src/Php80/bootstrap.php
- tests/Php80/Php80Test.php
Waiting for https://wiki.php.net/rfc/str_contains RFC.
> [PHP 8.0] add `str_contains` function

- CHANGELOG.md
- src/Iconv/bootstrap.php
- src/Intl/Grapheme/bootstrap.php
- src/Intl/Idn/bootstrap.php
- src/Mbstring/bootstrap.php
- src/Php56/bootstrap.php
- src/Uuid/bootstrap.php
> Fix support for preloading

- CHANGELOG.md
- src/Uuid/Uuid.php
- tests/Uuid/UuidTest.php
So that we can pretend to have a truely portable polyfill.
> [uuid] provide compat with 32bit systems

- src/Uuid/Uuid.php
Similar to https://github.com/symfony/symfony/pull/36070
> [uuid] improve base convertion logic for 32-bit systems

- CHANGELOG.md
- src/Intl/Normalizer/Normalizer.php
- src/Intl/Normalizer/Resources/stubs/Normalizer.php
- tests/Intl/Normalizer/NormalizerTest.php
Should help remove some code from #267 
/cc @TRowbotham
> Fix accuracy of Normalizer::isNormalized()

- .travis.yml
- tests/Intl/Normalizer/NormalizerTest.php
- tests/Uuid/UuidTest.php
> [Travis] test on bionic

- composer.json
- src/Apcu/composer.json
- src/Ctype/composer.json
- src/Iconv/composer.json
- src/Intl/Grapheme/composer.json
- src/Intl/Icu/composer.json
- src/Intl/Idn/composer.json
- src/Intl/MessageFormatter/composer.json
- src/Intl/Normalizer/composer.json
- src/Mbstring/composer.json
- src/Php54/composer.json
- src/Php55/composer.json
- src/Php56/composer.json
- src/Php70/composer.json
- src/Php71/composer.json
- src/Php72/composer.json
- src/Php73/composer.json
- src/Php74/composer.json
- src/Php80/composer.json
- src/Util/composer.json
- src/Uuid/composer.json
- src/Xml/composer.json
Waiting for the substree-splitter to sync the "main" branch before merging.
> Update branch-alias for main + v1.19

- .travis.yml
- appveyor.yml
Our Travis configuration does not reflect the new main branch. Let's fix this.
> Fix Travis build for the main branch

- src/Intl/Grapheme/Grapheme.php
grapheme_position() currently uses iconv/mbstring strpos implementations to look for the needle. However, this is not necessary: For UTF-8, we can use the normal strpos functions (as long as we also do the following substr using the normal functions).
This cuts off 25% of the runtime from symfony_demo /en/blog without intl. iconv_strpos is *extremely* slow.
> Optimize grapheme polyfill

- src/Uuid/Uuid.php
- tests/Uuid/UuidTest.php
This PR adjusts the UUID polyfill to the extension's behavior on PHP 8.
> Fix UUID polyfill for PHP 8

- src/Intl/Normalizer/Resources/stubs/Normalizer.php
> Sync values of Normalizer::* consts

- CHANGELOG.md
- composer.json
- src/Apcu/composer.json
- src/Ctype/composer.json
- src/Iconv/composer.json
- src/Intl/Grapheme/composer.json
- src/Intl/Icu/composer.json
- src/Intl/Idn/composer.json
- src/Intl/MessageFormatter/composer.json
- src/Intl/Normalizer/composer.json
- src/Mbstring/composer.json
- src/Php72/composer.json
- src/Php73/composer.json
- src/Php80/composer.json
- src/Php81/LICENSE
- src/Php81/Php81.php
- src/Php81/README.md
- src/Php81/bootstrap.php
- src/Php81/composer.json
- src/Util/composer.json
- src/Uuid/composer.json
- src/Xml/composer.json
- src/bootstrap.php
- tests/Php81/Php81Test.php
https://wiki.php.net/rfc/is_list
> Add polyfill-php81

- src/Php81/bootstrap.php
> [PHP 8.1] add enum_exists()

- src/Mbstring/bootstrap.php
- src/Mbstring/bootstrap80.php
- tests/Mbstring/MbstringTest.php
This pull request fixes the TypeError from #351.
> [mbstring] add return value to mb_parse_str (#351)

- src/Php80/bootstrap.php
- tests/Php80/Php80Test.php
> Allow null in str_*() functions

- CHANGELOG.md
- README.md
- src/Php80/PhpToken.php
- src/Php80/Resources/stubs/PhpToken.php
- tests/Php80/PhpTokenTest.php
Initial issue #376 
Tests PHP 8
> [Php80] Add PhpToken polyfill

- tests/Intl/Idn/IdnTest.php
The IDNA [test file](https://www.unicode.org/Public/idna/15.0.0/IdnaTestV2.txt) for Unicode 15.0.0 has started using escaped
unicode character sequences. The [spec](https://www.unicode.org/reports/tr46/#Format) says that they can be in the form
of either \uXXXX or \x{XXXX}.
Additionally, remove a now irrelevant conditional that worked around a bug in previous test files.
> Support escaped unicode character sequences in idna test files

- tests/Ctype/CtypeTest.php
- tests/Intl/Icu/AbstractCollatorTest.php
- tests/Intl/Icu/AbstractIcuTest.php
- tests/Intl/Icu/AbstractIntlDateFormatterTest.php
- tests/Intl/Icu/AbstractNumberFormatterTest.php
- tests/Intl/Icu/IntlDateFormatterTest.php
- tests/Intl/Icu/NumberFormatterTest.php
- tests/Intl/Icu/Verification/NumberFormatterTest.php
- tests/Intl/Idn/IdnTest.php
- tests/Intl/MessageFormatter/MessageFormatterTest.php
- tests/Php73/Php73Test.php
- tests/Php80/Php80Test.php
- tests/Php82/SensitiveParameterValueTest.php
- tests/Php83/Php83Test.php
- tests/Uuid/UuidTest.php
Preparing for upcoming PHPUnit 10 changes
> [Tests] Use static data providers

- .github/workflows/tests.yml
- src/Php82/Php82.php
- src/Php82/README.md
- src/Php82/bootstrap.php
- tests/Php82/Php82Test.php
This PR adds ODBC functions added in php/php-src#8307.
> Add odbc_connection_string_*() functions
