src/Util/Binary.php
There is little to no cost, since you're already proxying these functions. So why couple to only one potential overload rather than support a more general case.
=> Always use mbstring if it is loaded, since other extensions can potentially overload core string fucntions

.travis.yml, README.md, appveyor.yml, composer.json, src/Apcu/LICENSE, src/Apcu/README.md, src/Apcu/Resources/stubs/APCUIterator.php, src/Apcu/bootstrap.php, src/Apcu/composer.json, src/Iconv/README.md, src/Intl/Grapheme/README.md, src/Intl/Icu/README.md, src/Intl/Normalizer/README.md, src/Mbstring/README.md, src/Php54/README.md, src/Php55/README.md, src/Php56/README.md, src/Php70/README.md, src/Util/TestListener.php, src/Xml/README.md, tests/Apcu/ApcuTest.php
Now that we know that `apc_*` functions are legacy and `apcu_*` is the only way in PHP7, I propose to move forward with this polyfill. Let's replace all usages of `apc_*` in Symfony and elsewhere by their `apcu_*` equivalent and add a deps on this new polyfill to cope with legacy `apc` users.
=> [APCu] A new polyfill for the legacy APC users

src/Php70/Php70.php
This ensures we never create the conditions for https://bugs.php.net/63206
I.e. never use set_error_handler's second argument.
=> [Php70] Workaround https://bugs.php.net/63206

src/Php54/bootstrap.php, tests/Php54/Php54Test.php
`class_uses` accepts both the class name and object instance as first argument, `class_exists` only accepts a class name. If an object instance is giving, the class is already autoloaded, so the other logic can be skipped.
=> Fix class_uses polyfill

src/Php54/Php54.php, tests/Php54/Php54Test.php
=> php54 polyfill hex2bin(): don't return false if nul bytes found

src/Php54/Php54.php, tests/Php54/Php54Test.php
Fixes the hex2bin implementation as per #47/#48.
This supersedes https://github.com/symfony/polyfill/pull/48.
=> Fix hex2bin return null

src/Php70/composer.json
Greetings from the Symfony Live Cologne Hackday. :-)
This is a followup to the merged PR #44. I have added `"paragonie/random_compat": "~1.0|~2.0"` to the composer.json file of the `Php70` subpackage. Currently, only the full polyfill package allows version 2 of that library while the subpackage sill indicated compatibility with version 1 only.
=> Allow paragonie/random_compat 2 in the php 7 subpackage as well

src/Intl/Grapheme/Grapheme.php, tests/Intl/Grapheme/GraphemeTest.php
See https://github.com/tchwork/utf8/pull/59
=> Fix tests for php 5.5.35/5.6.21/7.0.6

src/Intl/Normalizer/Normalizer.php, tests/Intl/Normalizer/NormalizerTest.php
=> Normalizer::decompose() should reorder "recursive" combining chars

src/Mbstring/Mbstring.php
Polyfilling the behavior in erroneous situation is going to be too much work for today,
yet, by silencing, we at least prevent custom error handlers from throwing exceptions here (like phpunit's when running tests).
=> Silence iconv_strlen() in mb_strlen() polyfill

src/Mbstring/Mbstring.php, src/Mbstring/bootstrap.php, tests/Mbstring/MbstringTest.php
As implemented in upcoming php 7.2, see:
- https://github.com/php/php-src/pull/1099
- https://github.com/php/php-src/pull/1100
=> Polyfills for mb_chr(), mb_ord() and mb_scrub()

src/Php72/bootstrap.php
all polyfills bootstrap checks PHP ver itself before trying to register polyfills, for 7.2 it;s missing
=> PHP 7.2 - boost bootstrap

README.md
#89 reordered some lines, but it did not keep both lines about `random_bytes` together
=> Fix the readme content

README.md, src/Php72/Php72.php, src/Php72/README.md, src/Php72/bootstrap.php, tests/Php72/Php72Test.php
As [discussed on php-internals](https://externals.io/message/99751) and implemented in https://github.com/php/php-src/pull/2611.
Implementation [borrowed from VarDumper](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/VarDumper/Cloner/VarCloner.php#L300).
=> [7.2] Add polyfill for spl_object_id()

.travis.yml
Travis does not provide PHP 5.3 anymore on Trusty.
=> Use the old precise environment for PHP 5.3 jobs

CHANGELOG.md, README.md, composer.json, src/Php70/README.md, src/Php70/Resources/stubs/SessionUpdateTimestampHandlerInterface.php
This interface is mostly undocumented, but is required to implement lazy writes and session fixation prevention.
=> Add SessionUpdateTimestampHandlerInterface polyfill

.travis.yml, README.md, composer.json, src/Apcu/composer.json, src/Iconv/composer.json, src/Intl/Grapheme/composer.json, src/Intl/Icu/composer.json, src/Intl/Normalizer/composer.json, src/Mbstring/composer.json, src/Php54/composer.json, src/Php55/composer.json, src/Php56/composer.json, src/Php70/composer.json, src/Php71/composer.json, src/Php72/composer.json, src/Php73/LICENSE, src/Php73/README.md, src/Php73/bootstrap.php, src/Php73/composer.json, src/Xml/composer.json, tests/Mbstring/MbstringTest.php, tests/Php73/Php73Test.php, tests/Php73/generator.php
As requested by @nicolas-grekas :)
Waiting for https://github.com/php/php-src/pull/3026
=> Add is_countable under PHP 7.3

src/Php72/Php72.php, tests/Php72/Php72Test.php
While investigating [this issue](https://github.com/symfony/symfony/issues/26210), I've noticed that polyfill implementation of `sapi_windows_vt100_support()` is simplified.
As per PHP source code, native function:
- requires the first argument to be a resource, emits a warning otherwise,
- requires the stream to be a file descriptor, emits an unanalyzable stream warning otherwise,
- checks whether the stream is a TTY after validations above.
This PR aligns the polyfill with the native function by:
- validating `$stream` argument to be a resource,
- checking if the stream type is a `STDIO`, returns `FALSE` otherwise,
- if stream is not `STDIO`, attempts to call `stream_select()` and emits the _unanalyzable stream_ warning when a `FALSE` gets returned in advance,
- performing validations …
=> [7.2] Add missing validation to sapi_windows_vt100_support()

src/Php70/Php70.php
`Php70::intArg` is used from `Php70` class only. make it private.
project search result: https://github.com/symfony/polyfill/search?q=intArg&type=Code
=> Php70: do not expose intArg

CHANGELOG.md, README.md, composer.json, src/Ctype/Ctype.php, src/Ctype/LICENSE, src/Ctype/README.md, src/Ctype/bootstrap.php, src/Ctype/composer.json, tests/Ctype/CtypeTest.php
This PR adds a ctype pollyfill as mentioned in https://github.com/symfony/symfony/issues/24168
A copy of https://github.com/BackEndTea/ctype-compat adapted to the standards of this project.
ping @nicolas-grekas
=> Add the ctype polyfill

composer.json, src/Php70/composer.json
`paragonie/random_compat` ships a [special version 9.99.99](https://github.com/paragonie/random_compat#version-99999) which is only installable on PHP ≥7.0. It consists of an empty `composer.json` and adds no files to the autoloader. It might provide a minor perfomance improvement.
=> Allow NOP version of paragonie/random_compat

CHANGELOG.md, src/Iconv/Iconv.php, tests/Iconv/IconvTest.php
=> fix infinite loop in `iconv()` polyfill when using translit mode

README.md, composer.json, src/Intl/MessageFormatter/LICENSE, src/Intl/MessageFormatter/MessageFormatter.php, src/Intl/MessageFormatter/README.md, src/Intl/MessageFormatter/Resources/stubs/IntlException.php, src/Intl/MessageFormatter/Resources/stubs/MessageFormatter.php, src/Intl/MessageFormatter/bootstrap.php, src/Intl/MessageFormatter/composer.json, tests/Intl/MessageFormatter/MessageFormatterTest.php
This is a fork of Yii's [fallback MessageFormatter](https://github.com/yiisoft/yii2/blob/master/framework/i18n/MessageFormatter.php) implementation, ported as a polyfill of intl's MessageFormatter. I also reformatted the code to make it more in line with our practices and added some notes if we want to push the polyfill forward. The test suite compares both native and PHP variants, with similar results.
Kudos to them!
ping @cebe and @samdark FYI
=> Add polyfill for Intl\MessageFormatter

src/Php73/bootstrap.php
First PR is [here](https://github.com/symfony/polyfill-php73/pull/1), where was discussion.
Q: The issue is that this mutates the internal pointer.
A: created [benchmark](https://github.com/symfony/polyfill-php73/pull/1#issuecomment-424145092) and implementation does not change internal pointer.
Q: about performance for small vs big arrays
A: look like implementation is [every time faster](https://github.com/symfony/polyfill-php73/pull/1#issuecomment-424217955)
This implementation is approx twice faster than cycle foreach.
Benchmark is [on my gist](https://gist.github.com/h4kuna/6353ce99bd45b9c5fcdf49ef6d0e3da8). 
Results on my machine.
```
array_key_last_symfony
0.1387140750885
array_key_last
0.055586814880371
```
=> array_key_last: improving performance

src/Intl/Idn/Idn.php
I'm currently working on a project where we have to deploy the application to servers with a strange configuration. The servers run php 5.6, but instead of the bundled `ext-intl` the very outdated version 1.1 of `pecl/intl` is installed.
If I install the polyfill there, the `bootstrap.php` scrit will find an already defined `idn_to_ascii` function and do nothing. This is why I'd like to force the usage of the polyfill code here.
The problem that I have is that the old `pecl/intl` does not define all constants. To be more precise, `INTL_IDNA_VARIANT_UTS46` is missing because version 1.1 did not yet support the `$variant` parameter.
In order to solve this problem for me, I have redefined all constants on the `Idn` class.
=> Redefine INTL_IDN_VARIANT_* constants on the Idn class

.travis.yml, src/Util/TestListener.php, src/Util/TestListenerForV5.php, src/Util/TestListenerForV6.php, src/Util/TestListenerForV7.php, src/Util/TestListenerTrait.php
This PR fixes support for PHPUnit 7.2 by adding a separate `TestListener` for each major PHPUnit version.
It should fix #144 and is based on #133.
=> add phpunit 7.2

src/Php73/bootstrap.php
Some composer plugins (like monorepo) will cause files to be loaded before the autoloader is fully registered, so class files must be manually loaded
=> ensure Php73 class is loaded for bootstrap

.travis.yml, README.md, composer.json, src/Mbstring/Mbstring.php, src/Mbstring/bootstrap.php, src/Php73/Php73.php, src/Php74/Php74.php, src/Php74/README.md, src/Php74/bootstrap.php, src/Php74/composer.json, tests/Mbstring/MbstringTest.php, tests/Php74/Php74Test.php
This PR adds new PHP 7.4 functions:
Closes #179 and replaces #178
=> add new PHP 7.4 functions

src/Mbstring/Mbstring.php, src/Php74/Php74.php, tests/Mbstring/MbstringTest.php, tests/Php74/Php74Test.php
`mb_strlen` + `mb_substr` can be very slow for large strings. In the common case of split length 1 and charset UTF=8 we can use `preg_split` instead.
Added an early exit to the function:
if (1 === $split_length && 'UTF-8' === $encoding) {
return preg_split('//u', $string, null, PREG_SPLIT_NO_EMPTY);
}
See https://3v4l.org/U6PPf
=> Optimization of mb_str_split

src/Php73/Php73.php
=> Ensure hrtime is monotonic

src/Php73/Php73.php
This reverts commit 64d2d7d5b4595443c1ad0c667597ea4f5ae1e7a5, reversing
changes made to b501e55fbc45de6bc4112efeb7cb5f4b6a283d7b.
/cc @GrahamCampbell FYI I just realized the implementation doesn't work:
microtime(false) return something like `0.00018200 1574780469`
casting this to float and comparing with the previous checks only the sub-seconds part. But it should account for seconds too.
That's why tests fail transiently on the CI.
Maybe we don't care about monotonicity eventually, do we?
=> Revert "bug #187 Ensure hrtime is monotonic (GrahamCampbell)"

CHANGELOG.md, src/Php55/Php55.php, tests/Php55/Php55Test.php
SHA1 has a 64 byte (512 bit) block size, not a 20 byte (160 bit) block size like you would expect.
Closes https://github.com/symfony/polyfill-php55/pull/3
=> Use correct block size for SHA1

CHANGELOG.md, src/Mbstring/Mbstring.php, tests/Mbstring/MbstringTest.php
=> [Mbstring] fix `mb_str_split()` ignoring new-line characters

.travis.yml, CHANGELOG.md, README.md, composer.json, src/Apcu/composer.json, src/Ctype/composer.json, src/Iconv/composer.json, src/Intl/Grapheme/composer.json, src/Intl/Icu/composer.json, src/Intl/Idn/composer.json, src/Intl/MessageFormatter/composer.json, src/Intl/Normalizer/composer.json, src/Mbstring/composer.json, src/Php54/composer.json, src/Php55/composer.json, src/Php56/composer.json, src/Php70/composer.json, src/Php72/composer.json, src/Php73/composer.json, src/Php74/composer.json, src/Php80/LICENSE, src/Php80/Php80.php, src/Php80/README.md, src/Php80/bootstrap.php, src/Php80/composer.json, src/Util/composer.json, src/Uuid/composer.json, src/Xml/composer.json, tests/Php80/Php80Test.php
This PR adds simple `fdiv()` implementation by suppressing warnings on the division, just like in original implementation: https://github.com/php/php-src/commit/e35bdb49121ac451384b6c443850ce67e7c5be63
This feature works only on PHP 7+ because suppressing warnings does not produce valid results and casting to string does not detect negative zero on older versions. 
Full logic implementation is available at https://github.com/IonBazan/polyfill/blob/php8-php5/src/Php80/Php80.php but lacks negative-zero detection for PHP 5. If anyone figures out how to detect it, we can simply replace `LogicException` with it.
=> PHP 8.0 - add fdiv() function polyfill

README.md, composer.json, src/Php80/README.md, src/Php80/Resources/stubs/ValueError.php, src/Php80/bootstrap.php, src/Php80/composer.json, tests/Php80/Php80Test.php
This change adds support for new PHP 8.0 features:
=> [PHP8.0] add ValueError and FILTER_VALIDATE_BOOL

CHANGELOG.md
The nested lists in the changelog are rendered incorrectly: https://github.com/symfony/polyfill/blob/babc827310d58cc42dea5574c0c7343075e2c861/CHANGELOG.md
According to GitHub's [Markdown Guide](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#nested-lists), nested lists must be intended "until the list marker character lies directly below the first character of the text in the item above it".
=> Fix markdown list formatting in changelog

src/Php80/bootstrap.php
PHP can be compiled without the `filter` extension, so there is a possibility that `FILTER_VALIDATE_BOOLEAN` isn't available.
=> Check if `FILTER_VALIDATE_BOOLEAN` is available

CHANGELOG.md, README.md, src/Php80/Php80.php, src/Php80/README.md, src/Php80/bootstrap.php, tests/Php80/Php80Test.php
This PR adds the function `preg_last_error_msg` added in [php-src/pull/5185](https://github.com/php/php-src/pull/5185)
_Note_: I only tested the cases that don't require special `.ini` settings as I didn't want to set them dynamically in the test suite.
=> [PHP 8.0] Add preg_last_error_msg function

CHANGELOG.md, src/Php80/README.md, src/Php80/Resources/stubs/Stringable.php
=> Add polyfill for PHP8's Stringable

CHANGELOG.md, src/Uuid/Uuid.php, src/Uuid/bootstrap.php, tests/Uuid/UuidTest.php
Note: on old libuuid version, the V5 format is broken. Ubuntu 18.04 is affected.
This has been fixed [here](https://github.com/karelzak/util-linux/commit/d6ddf07d31dfdc894eb8e7e6842aa856342c526e).
You can test your distribution with:
```
uuidgen -s -n ec07aa88-f84e-47b9-a581-1c6b30a2f484 -N "the name"
```
You must got:
```bash
851def0c-b9c7-55aa-a991-130e769ec0a9
```
Some tests:
```
// python:          851def0c-b9c7-55aa-a991-130e769ec0a9
// go:              851def0c-b9c7-55aa-a991-130e769ec0a9
// ramsey:          851def0c-b9c7-55aa-a991-130e769ec0a9
// sf:              851def0c-b9c7-55aa-a991-130e769ec0a9
// libuuid 19.10:   851def0c-b9c7-55aa-a991-130e769ec0a9
// libbuuid arch:   851def0c-b9c7-55aa-a991-130e769ec0a9
// libuuid 18.04:   851def0c-b9c7-55aa-8991-130e769ec0a9
// pecl …
```
=> [UUID] Added support for V3 and V5

README.md, src/Php80/Php80.php, src/Php80/README.md, src/Php80/bootstrap.php, tests/Php80/Php80Test.php
=> [Php80] Add get_debug_type()

src/Uuid/Uuid.php
Follows https://dev.to/fredbouchery/performance-des-uuids-29dj
=> [uuid] improve perf

src/Php72/Php72.php, tests/Php72/Php72Test.php
spl_object_hash will be a string such as
`000000001b19a247000000004e677fa5`.
The first half is 8 to 16 zero-padded **hex digits** of
data (PHP_INT_SIZE=4 **bytes** on 32-bit systems, 8 on 64-bit systems)
This meant that this polyfill for spl_object_id previously couldn't accurately
represent values that were greater than 65536 (`16**4`) on 32-bit systems,
~~or 4294967296 (`16**8`) on 64-bit systems.~~
This was noticed because 32-bit tests failed for Phan in php 7.1.
(https://github.com/phan/phan/blob/master/src/spl_object_id.php had no
issues before the dependency on symfony/polyfill-72 was added for a
different function)
- Aside: The object handle of `struct _zend_object` was a uint32_t in php 7.1,
so it's always 8 hex digits for official php builds.
=> Fix the polyfill for spl_object_id()

src/Php80/Php80.php, src/Php80/bootstrap.php, tests/Php80/Php80Test.php
Adds polyfills for str_starts_with() and str_ends_with() functions added in PHP 8.0.
RFC: https://wiki.php.net/rfc/add_str_starts_with_and_ends_with_functions
Tests from PHP source:
- ext/standard/tests/strings/str_starts_with.phpt
- ext/standard/tests/strings/str_ends_with.phpt
Sample implementation: https://php.watch/versions/8.0/str_starts_with-str_ends_with
*Marking this PR draft because the RFC voting has yet to be closed (on May 4)*
=> Add polyfill for PHP 8's str_starts_with() and str_ends_with() functions

README.md, src/Php80/README.md
I'm sorry the PR #250 did not update the root readme file with the two new functions. This commit changes it.
=> Update `README.md` file with the new str_starts_with and str_ends_with

src/Php80/Php80.php
Refs https://github.com/symfony/polyfill/pull/250#discussion_r418961105
The benchmark http://sandbox.onlinephpfunctions.com/code/8d3dd885b40946d55e40aa918ed900f2a8d9741a shows that v 2 avoids extra memory allocation (like the native implementation), and is faster (significantly for large strings).
=> [PHP 8.0] Use substr_compare() for str_ends_with()

CHANGELOG.md, src/Intl/Idn/Idn.php, tests/Intl/Idn/IdnTest.php
=> Fail on leading or trailing hyphen-minus (RFC 3492)

src/Apcu/bootstrap.php, src/Ctype/bootstrap.php, src/Iconv/bootstrap.php, src/Intl/Grapheme/bootstrap.php, src/Intl/Icu/bootstrap.php, src/Intl/Idn/bootstrap.php, src/Intl/Normalizer/bootstrap.php, src/Mbstring/bootstrap.php, src/Php56/bootstrap.php, src/Php72/bootstrap.php, src/Php80/bootstrap.php, src/Uuid/bootstrap.php
As originally discussed in https://github.com/symfony/polyfill-mbstring/pull/6 and later in https://github.com/symfony/polyfill/pull/251 in some scenarios it may be better to check for each constant/function before defining it. Such scenarios are typically those where some project or a library defines its polyfills for some parts of extension functionality but not all of it.
Probably the most popular example is WordPress, defining some polyfills in `wp-includes/compat.php` but not including complete functionalities (i.e. it defines only a few `mb_` functions). Plugin developers then may need other `mb_` functions and need to load those that WordPress didn't.
There may be some performance concerns but it seems that checks such as `function_exists` are [very …
=> Add separate checks for all polyfilled functions and constants

CHANGELOG.md, README.md, src/Php72/README.md, src/Php72/bootstrap.php, tests/Php72/Php72Test.php
Fix #223
The values are the same on 32b and 64b systems.
They differ only on very exotic and old architectures (VAX/IBM floats).
=> Add polyfill for `PHP_FLOAT_*` constants

README.md, src/Php80/Php80.php, src/Php80/README.md, src/Php80/bootstrap.php, tests/Php80/Php80Test.php
Resolves #259 
PHP 8.0 output for reference:
```
php > $res = fopen('test', 'w');
php > var_dump((int) $res, get_resource_id($res));
int(2)
int(2)
php > fclose($res);
php > var_dump((int) $res, get_resource_id($res));
int(2)
int(2)
php > $res = 10;
php > var_dump((int) $res, get_resource_id($res));
PHP Warning:  Uncaught TypeError: get_resource_id(): Argument #1 ($res) must be of type resource, int given in php shell code:1
Stack trace:
#0 php shell code(1): get_resource_id(10)
#1 {main}
thrown in php shell code on line 1
Warning: Uncaught TypeError: get_resource_id(): Argument #1 ($res) must be of type resource, int given in php shell code:1
Stack trace:
#0 php shell code(1): get_resource_id(10)
#1 {main}
thrown in php shell code on line 1
```
=> [PHP 8.0] add `get_resource_id` function

CHANGELOG.md, src/Iconv/bootstrap.php, src/Intl/Grapheme/bootstrap.php, src/Intl/Idn/bootstrap.php, src/Mbstring/bootstrap.php, src/Php54/bootstrap.php, src/Php55/bootstrap.php, src/Php56/bootstrap.php, src/Php70/bootstrap.php, src/Php71/bootstrap.php, src/Php72/bootstrap.php, src/Php73/bootstrap.php, src/Php74/bootstrap.php, src/Php80/bootstrap.php, src/Uuid/bootstrap.php
Fix #262
Best to [ignore whitespace](https://github.com/symfony/polyfill/pull/263/files?w=1) when reviewing.
=> Fix declaring extra constants when `intl` is loaded

src/Apcu/README.md, src/Apcu/bootstrap.php, tests/Apcu/ApcuTest.php
This is the correct case defined in the source code: https://github.com/krakjoe/apcu/blob/1f98e34d93/apc_iterator.h#L29
This is an attempt to fix errors that a project started to report on PHPStan `v0.12.26`:
```
------ ------------------------------------------------------------------
Line   src/State/StateStorage.php
------ ------------------------------------------------------------------
6      Class APCUIterator referenced with incorrect case: APCuIterator.
109    Class APCUIterator referenced with incorrect case: APCuIterator.
------ ------------------------------------------------------------------
```
=> Align `APCuIterator` case with its implementation

README.md, src/Php80/README.md, src/Php80/Resources/stubs/UnhandledMatchError.php
Along with the `match` expression syntax in PHP 8, it [registers](https://github.com/php/php-src/blob/c2d3cd2595481af4b2edd7cf26fb148de2d475aa/Zend/zend_exceptions.c#L819-L820) a new exception class `UnhandledMatchError` that extends `\Error`.
While the `match` expression itself cannot be polyfilled, we can backport this new class for the feature parity, so exceptions can be unserialized, or exceptions can be thrown in other code if they choose to throw `\UnhandledMatchError` exceptions.
- [RFC](https://wiki.php.net/rfc/match_expression_v2)
- [Implementation](https://github.com/php/php-src/blob/c2d3cd2595481af4b2edd7cf26fb148de2d475aa/Zend/zend_exceptions.c#L819-L820)
- [`match` expressions # `UnhandledMatchError`](https://php.watch/versions/8.0/match-expression#UnhandledMatchError)
- PR …
=> Add `UnhandledMatchError` exception class

src/Intl/Idn/Idn.php, tests/Intl/Idn/IdnTest.php
Fixes #279.
The problem is this line: https://github.com/symfony/polyfill/blob/master/src/Intl/Idn/Idn.php#L162 and only affects `idn_to_ascii`. Strictly speaking, this isn't part of the spec. The fix is to remove this conditional statement.
The reason why it is here is an assumption that I made regarding a discrepancy between what the spec produces and what the test cases expect. The problem that I was trying to solve is that the tests expect that a label that contains a "?" and also has an error should remain in it's Unicode form, however, the spec says to always convert the label to it's ASCII form. There are roughly 200 test cases where this is the case. As a result of this, I extrapolated this to mean that labels containing URL delimiters and had an error should stay in their Unicode …
=> Don't force labels containing URL delimiters to stay in their Unicode form when using idn_to_ascii

src/Intl/Idn/Idn.php
Fixes #278.
Sometimes we can get into an awkward configuration where `ext-intl` is enabled, but is compiled with a version of ICU < 4.6, which means that a number of constants aren't defined and the polyfill doesn't get loaded and therefore doesn't define the constants for us. This causes breakage for users using the internal API. Fix this by avoiding the use of any `IDNA_*` constants.
@bmack let me know if this fixes the issue for you.
=> Avoid using any IDNA constants in the internal polyfill implementation

CHANGELOG.md, src/Php80/Resources/stubs/Attribute.php, tests/Php80/Php80Test.php
Code which works with both php 7 and 8 may need to use the class constants or
instances of the attribute class outside of attribute declarations. E.g.
// This line throws without a polyfill for Attribute.
const FUNCTIONLIKE_ATTRIBUTES = Attribute::TARGET_FUNCTION | Attribute::TARGET_METHOD;
#[Attribute(FUNCTIONLIKE_ATTRIBUTES)]
function example() { }
For #235
Attribute had real types in the actual constructor, is final, etc. This polyfill is currently targeting php 7+, so the real type `int $flags` was used.
=> Add a polyfill for the Attribute class

CHANGELOG.md, src/Mbstring/Mbstring.php, tests/Mbstring/MbstringTest.php
https://www.php.net/strrchr has the signature
`strrchr ( string $haystack , mixed $needle ) : string`
Passing the unused 3rd argument becomes an ArgumentCountError in php 8.0
Detected via static analysis
=> Fix php8 error passing too many arguments to strrchr

CHANGELOG.md, src/Php80/Resources/stubs/Stringable.php
Fix https://github.com/symfony/symfony/issues/38588
=> Skip loading `Stringable` on PHP 8

src/Iconv/Iconv.php, tests/Iconv/IconvTest.php
`iconv_substr` is changed in [PHP 8.0 to return an empty string on out-of-bound offsets](https://php.watch/versions/8.0/substr-out-of-bounds).
This commit updates the tests with `@requires` annotatios and polyfill updates to make sure the return results are in line with native function behavior.
Related: #288
=> iconv: Adjust `iconv_substr` PHP 8 compatibility

src/Php73/bootstrap.php
Suggested by @donaldinou   (fix #293 )
up to 6 times faster on big arrays like `array_fill(0, 1024*1024, 'hello');`
https://blackfire.io/profiles/05de3d1f-0193-462d-839f-361c4c206a0d/graph
=> Improve performances of array_key_last

src/Iconv/Iconv.php, src/Intl/Grapheme/Grapheme.php, tests/Iconv/IconvTest.php, tests/Intl/Grapheme/GraphemeTest.php
`grapheme_substr` is changed in [PHP 8.0 to return an empty string on out-of-bound offsets](https://php.watch/versions/8.0/substr-out-of-bounds#grapheme_substr).
This commit updates the tests with `@requires` annotations and polyfill updates to make sure the return results are in line with native function behavior. In PHP 8, an empty string (`""`) is returned if the length parameter is out of bounds of the given string. Prior to PHP 8.0, boolean `false` is returned.
Related: #288
=> Intl Grapheme: Adjust `grapheme_substr` PHP 8 compatibility

CHANGELOG.md, src/Ctype/bootstrap.php, src/Iconv/bootstrap.php, src/Intl/Grapheme/bootstrap.php, src/Intl/Icu/bootstrap.php, src/Intl/Normalizer/bootstrap.php, src/Mbstring/Resources/mb_convert_variables.php8, src/Mbstring/bootstrap.php, src/Php54/bootstrap.php, src/Php55/bootstrap.php, src/Php56/bootstrap.php, src/Php70/bootstrap.php, src/Php71/bootstrap.php, src/Php72/bootstrap.php, src/Php73/bootstrap.php, src/Php74/bootstrap.php, src/Php80/bootstrap.php
With PHP 8 coming, we need to have function/methods parameters names consistent between polyfills and the original implementations.
I'm not sure if this is all of it yet.
see: 
https://github.com/php/php-tasks/issues/23
https://github.com/php/php-tasks/issues/16
=> Fix the name of arguments for PHP 8

src/Iconv/Iconv.php, src/Intl/Idn/Idn.php
A very minor improvement in code clarity. Removed `else` and `elseif` blocks where the previous code block has `return`, `continue`, or `throw` calls, where the execution flaw is halted anyway. 
Thank you.
=> Code cleanup: Remove redundant else/elseif blocks

src/Util/TestListener.php, src/Util/TestListenerForV9.php, tests/Uuid/UuidTest.php
Our tests currently don't work on php 8. I'd like to give it a try to fix this.
=> Fix CI for php 8

tests/Php72/Php72Test.php, tests/Php74/Php74Test.php
Some functions that were added with PHP 7.2/7.4 have been made a bit stricter with PHP 8: They now trigger `TypeError`s and `ValueError`s on invalid input.
I think the PHP 7.2 polyfill should implement the polyfilled functions as they were shipped with PHP 7.2. Because of that, I think we can skip the affected tests on PHP 8.
=> Skip tests of the 7.2/7.4 polyfills that cause Errors on PHP 8

CHANGELOG.md, src/Apcu/bootstrap80.php, src/Iconv/bootstrap80.php, src/Intl/Grapheme/bootstrap80.php, src/Intl/Icu/bootstrap80.php, src/Intl/Idn/bootstrap80.php, src/Intl/Normalizer/bootstrap80.php, src/Mbstring/bootstrap80.php, src/Util/TestListenerTrait.php, src/Uuid/bootstrap80.php
Fixes https://github.com/symfony/polyfill/issues/329
I decided to not trigger any deprecation because that'd be adding overhead for something that is already reported by native PHP.
=> Always accept null values on PHP 8

src/Mbstring/Mbstring.php
The mbstring polyfill does not require the iconv polyfill due to the size of the package and the fact that most systems will have the native ext-iconv (it is enabled by default in PHP).
Using fully qualified calls gives a better error message when the iconv extension is missing and the polyfill is not installed, which makes it easier to solve the issue.
Refs #342
=> Use fully-qualified iconv calls in the mbstring polyfill

CHANGELOG.md, README.md, src/Php81/README.md, src/Php81/bootstrap.php, tests/Php81/Php81Test.php
This PR adds `MYSQLI_REFRESH_REPLICA` constant which equals to `MYSQLI_REFRESH_SLAVE`. This will allow users to move to new naming convention even before it is deprecated by PHP and MySQL.
=> [PHP 8.1] Add MYSQLI_REFRESH_REPLICA polyfill

src/Php81/README.md, src/Php81/Resources/stubs/ReturnTypeWillChange.php, src/Php81/composer.json
I'd like to add this nice little class that I've found in my PHP 8.1 nightly build.
```php
dump(new ReflectionClass(\ReturnTypeWillChange::class));
```
=> Add ReturnTypeWillChange attribute

src/Mbstring/Mbstring.php
While #322 correctly introduced the ValueError thrown for incorrect values, the exception is also thrown for various cases where the input to the function is actually accepted. 
While this PR does in no way improve the functionality of the mb_substitute_character polyfill (which might be needed to at some point, as the input is not used at all, currently), it does improve the compatibility with the function that is being polyfilled.
=> [Mbstring] fix throwing from mb_substitute_character on PHP >= 8

src/Php81/Php81.php, tests/Php81/Php81Test.php
Hey there,
I've used this function quite a lot and I see a massive performance gap between [webmozart/assert](https://github.com/webmozarts/assert/blob/f07851c5b43e4cb502c24068620e9af6cbdd953f/src/Assert.php#L1823) and this polyfill.
https://3v4l.org/ruYVL
This polyfill covers a niche case with `\NAN` and thus, my previous attempt in #355 failed.
So I've worked out another solution which is still a little bit faster than the current one.
https://3v4l.org/KiCg2
=> [Php81] Optimize `array_is_list`

src/Php80/Resources/stubs/UnhandledMatchError.php, src/Php80/Resources/stubs/ValueError.php
Not redeclaring polyfilled classes when PHP version is 8.0 or above.
The same approach is used for the Stringable interface in [this commit](https://github.com/symfony/polyfill/commit/8a3e84999b869b30bc8688eb3784681028007d5e).
One of my scripts runs [`opcache_compile_file`](https://www.php.net/manual/en/function.opcache-compile-file.php) on vendor files, including symfony. I'm in the process of upgrading to PHP 8. Running `opcache_compile_file` on either of the modified files causes a fatal error `Fatal error: Cannot declare class ValueError/UnhandledMatchError, because the name is already in use`.
That's not the case on PHP versions below 8.
=> [PHP80] Prevent redefinition of PHP 8.0 classes

src/Mbstring/Mbstring.php
> Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
=> Passing null to strpos() throws deprecation on PHP 8.1

src/Iconv/bootstrap.php, src/Iconv/bootstrap80.php, tests/Iconv/IconvTest.php, tests/Mbstring/MbstringTest.php
1. `mb_decode_mimeheader` has only one argument (see https://www.php.net/manual/en/function.mb-decode-mimeheader.php).
Calling it with 3 arguments triggers following error: `mb_decode_mimeheader() expects exactly 1 argument, 3 given in ./vendor/symfony/polyfill-iconv/bootstrap80.php at line 57`.
2. `iconv_mime_decode()` `$encoding` argument is not correctly handled. Indeed, it should be used to convert result in expected encoding.
=> Fix iconv_mime_decode() while using mbstring extension

phpunit.xml.dist
Update DTD to version declared in `required-dev` in `composer.json` to fix IDE's warnings.
Remove attribute `backupGlobals="false"` because it's default value.
=> Fix outdated DTD in configuration

src/Intl/Icu/DateFormat/QuarterTransformer.php, tests/Intl/Icu/AbstractIntlDateFormatterTest.php
As per [1], the QQQQQ and qqqqq quarter patterns are supposed to convert
quarter into numbers (1, 2, 3, or 4). Until vertion 70.1, ICU carried a
bug [2] which would make those patterns to convert into the wrong string,
mimicking the behavior of the QQQQ pattern. The issue has been fixed
upstream [3] and released in ICU 70.1.
This patch adjusts the pattern resolution according to the ICU version
being used by intl.
[1] https://unicode-org.github.io/icu/userguide/format_parse/datetime/#date-field-symbol-table
[2] https://unicode-org.atlassian.net/browse/ICU-21647
[3] https://github.com/unicode-org/icu/commit/dcfdaca46c1e3cc08764ad1d85f321ad0c27ae16
Signed-off-by: Athos Ribeiro <athos.ribeiro@canonical.com>
=> Fix QQQQQ date format

src/Mbstring/Mbstring.php, src/Php74/Php74.php
> preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated
=> Passing null to preg_split() throws deprecation on PHP 8.1

README.md, src/Php82/README.md, src/Php82/Resources/stubs/AllowDynamicProperties.php
Provides a polyfill for `AllowDynamicProperties` attribute introduced in PHP 8.2.
RFC: https://wiki.php.net/rfc/deprecate_dynamic_properties
Fixes: #403
=> Polyfill AllowDynamicProperties attribute

src/Intl/Icu/IntlDateFormatter.php
Following bug fix on Symfony Intl component, see https://github.com/symfony/symfony/pull/46730 for the full description.
=> [Intl] Fix the IntlDateFormatter::formatObject signature

tests/Php72/Php72Test.php
This change skips comparing `PHP_FLOAT_MIN` and `PHP_FLOAT_MAX` constants on PHP 7.3 and higher as they changed their values. The test will only be run on PHP 7.1 (using provided polyfill) and PHP 7.2 (using native PHP values).
These constants depend on `DBL_MIN` and `DBL_MAX` which might change depending on the platform and/or compiler. I believe the values have changed in PHP 7.3 due to gcc update or some other time-related factor.
=> Skip PHP_FLOAT_* checks on PHP 7.3+

.github/workflows/tests.yml, README.md, composer.json, src/Php83/LICENSE, src/Php83/Php83.php, src/Php83/README.md, src/Php83/bootstrap.php, src/Php83/composer.json, src/bootstrap.php, tests/Php83/Php83Test.php
This PR adds `json_validate()` polyfill - see: https://wiki.php.net/rfc/json_validate.
Tests examples were taken from the php-src implementation. 
Test failures are unrelated.
Float tests are fixed in #417, remaining PHP 8.2 mbstring test can be sorted out separately.
=> PHP 8.3: json_validate polyfill

src/Php83/Php83.php, tests/Php83/Php83Test.php
Even though the error message for json_decode will say 'Argument #3 ($depth) must be less than 2147483647', the actual behavior of the method allows this (https://3v4l.org/QdfHt) and the official online documentation also confirms this behavior (https://www.php.net/manual/en/function.json-decode.php ' The value must be greater than 0, and less than or equal to 2147483647'). I have not been able to confirm whether 2147483647 is accepted by json_decode on a 32 bit system (where it is equal to PHP_MAX_INT) as I do not have access to one. (3v4l also uses 64 bit PHP)
=> Fix json_validate rejecting valid maximum depth

CHANGELOG.md, README.md, composer.json, src/Apcu/composer.json, src/Ctype/composer.json, src/Iconv/composer.json, src/Intl/Grapheme/composer.json, src/Intl/Icu/composer.json, src/Intl/Idn/composer.json, src/Intl/MessageFormatter/composer.json, src/Intl/Normalizer/composer.json, src/Mbstring/composer.json, src/Php72/composer.json, src/Php73/composer.json, src/Php74/composer.json, src/Php80/composer.json, src/Php81/README.md, src/Php81/Resources/stubs/CURLStringFile.php, src/Php81/composer.json, src/Php82/composer.json, src/Php83/composer.json, src/Util/composer.json, src/Uuid/composer.json, src/Xml/composer.json, tests/Php81/CURLStringFileTest.php, tests/Php81/fixtures/curl-echo-server.php
PHP 8.1 adds a [new class `CURLStringFile`](https://php.watch/versions/8.1/CURLStringFile), that works similar to `CURLFile`, but does not require a _path_ to a file, and accepts a string of file contents instead. This can be polyfilled with a `CURLFile` sub class that uses a `data://` URI inside a constructure and calling `CURLFile::__construct` with that data URI.
Closes #333.
I will leave this as a draft because I'm not sure how to write tests for this. I'm thinking a PHP CLI server that echoes `$_FILES`, and a test that checks the returned content for file(s) that it uploaded.
=> [PHP 8.1] Add `CURLStringFile` polyfill

src/Mbstring/Mbstring.php, tests/Mbstring/MbstringTest.php
I tried to address the https://github.com/symfony/polyfill/issues/422 issue.
First time on that project. I'm not sure about what I've done because I'm afraid we cannot do anything for PHP <7.2.
=> add mb_check_encoding with array value

README.md, composer.json, src/Php83/README.md, src/Php83/Resources/stubs/Override.php, src/Php83/composer.json
Adds `#[\Override]` attribute introduced in PHP 8.3: https://wiki.php.net/rfc/marking_overriden_methods
Failing tests are unrelated
=> [PHP 8.3] Add `#[\Override]` attribute

README.md, src/Mbstring/Mbstring.php, src/Mbstring/bootstrap.php, src/Mbstring/bootstrap80.php, src/Php83/Php83.php, src/Php83/README.md, src/Php83/bootstrap.php, tests/Mbstring/MbstringTest.php, tests/Php83/Php83Test.php
Polyfills the `mb_str_pad()` function added in PHP 8.3: https://wiki.php.net/rfc/mb_str_pad
Test cases were taken from the RFC implementation and adapted to PHPUnit.
=> [PHP 8.3] Polyfill mb_str_pad()
